# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Source alias
if [ -f $HOME/.bash_alias ]; then
	. $HOME/.bash_alias
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# Setup ibus
ibus-daemon -d
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

# GOPATH
export GOPATH=$HOME/go
export GOROOT=$HOME/go1.6

export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

if [ -f `which powerline-daemon` ]; then
	powerline-daemon -q
	POWERLINE_BASH_CONTINUATION=1
	POWERLINE_BASH_SELECT=1
	. /usr/share/powerline/bash/powerline.sh
fi
